baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Artefaktas AI Plugin'
theme = 'hugo-paper'
ignoreFiles = ["/content/posts/templates.*"]
[menu]

  [[menu.main]]
    identifier = "main"
    name = "Main"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/posts/about"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/tags/posts/"
    weight = 3
  [[menu.main]]
    identifier = "contacts"
    name = "Contacts"
    url = "/posts/contacts"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
